INHERIT: docs/base_docs/mkdocs.yml
site_name: EchoTherm Documentation
repo_url: https://github.com/EchoMAV/echotherm_docs
edit_uri: edit/master/echotherm_docs/
repo_name: echomav/echotherm_docs
nav:
    - Overview: overview.md    
    - Quick Start: quickstart.md
    - Tech Specs: techspecs.md
    - Hardware Guide: hardware.md
    - Software Guide: software.md
    - Pinouts: electrical.md
    - Mechanical: mechanical.md
theme:
  custom_dir: overrides
  features:
    - toc.integrate
