theme:
  name: material
  logo: base_docs/assets/echomav-small-black-bg.png
  favicon: base_docs/assets/echomav_fav.png
  features:
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.instant
#    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
    - content.action.edit
    - content.action.view
    - content.code.copy    
  language: en
  palette:    
      primary: black
      accent: blue
  
extra:
  homepage: https://echomav.com
  version:
    provider: mike

  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/echomav


extra_css:
  - base_docs/stylesheets/extra.css

markdown_extensions:
  toc:
    permalink: true
  pymdownx.highlight:
      anchor_linenums: true
  pymdownx.inlinehilite: {}
  pymdownx.snippets: {}
  pymdownx.tabbed:
      alternate_style: true 
  admonition: {}
  pymdownx.arithmatex:
      generic: true
  footnotes: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.mark: {}
  attr_list: {}
  footnotes: {}
  md_in_html: {}
  pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  glightbox: {}
  open-in-new-tab: {}
  search: {}

copyright: |
  &copy; 2025 <a href="echomav.com"  target="_blank" rel="noopener">EchoMAV, LLC</a>
